---

- name: Create/invoke script virtualenv
  pip: name={{ item }} virtualenv={{ galaxy_tools_base_dir }}/venv virtualenv_command="{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  with_items:
    - pyyaml
    - bioblend

- name: Place the datasets management script
  copy: src=import_into_library.py dest={{ galaxy_tools_base_dir }}/import_into_library.py

- name: Import datasets into a library
  command: chdir={{ galaxy_tools_base_dir }} {{ galaxy_tools_base_dir }}/venv/bin/python import_into_library.py -l {{ item.library_label }} -u {{ item.url }} -a {{ galaxy_tools_api_key }} -g {{ galaxy_tools_galaxy_instance_url }}
  with_items:
    - "{{ galaxy_datasets_dict }}"

- name: Remove datasets script
  file: dest={{ galaxy_tools_base_dir }}/import_into_library.py state=absent
